# 10 minutes to pandas
## pandas 的数据类型

## `Series` 序列


In [1]:
import numpy as np
import pandas as pd
import sys
sys.path.append("..") 



s = pd.Series([1,4,2,'aab',3.23,np.nan])
print(s)

0       1
1       4
2       2
3     aab
4    3.23
5     NaN
dtype: object


Creating a `Series` by passing a list of values, letting pandas create a default integer index:

通过一个List来创建序列 `Series`

In [2]:
s = pd.Series([1,4,2,3.23,np.nan])
print(s)

0    1.00
1    4.00
2    2.00
3    3.23
4     NaN
dtype: float64


## `DataFrame`
Creating a DataFrame by passing a NumPy array, with a datetime index and labeled columns:

### `DataFrame` 

In [3]:
dates = pd.date_range('20190918', periods = 12)
print(dates)

DatetimeIndex(['2019-09-18', '2019-09-19', '2019-09-20', '2019-09-21',
               '2019-09-22', '2019-09-23', '2019-09-24', '2019-09-25',
               '2019-09-26', '2019-09-27', '2019-09-28', '2019-09-29'],
              dtype='datetime64[ns]', freq='D')


In [4]:
data_frame = pd.DataFrame(np.random.normal(1, 0.01, (12,3)), index = dates, columns = list('ABC'))

In [5]:
print(data_frame)

                   A         B         C
2019-09-18  0.989936  0.990347  1.005533
2019-09-19  0.984528  0.980366  1.018356
2019-09-20  1.016322  1.003045  0.998361
2019-09-21  0.993233  0.993873  0.992124
2019-09-22  0.984321  0.998008  1.004511
2019-09-23  0.994078  0.985869  0.990937
2019-09-24  0.995265  1.009943  1.005325
2019-09-25  0.997671  1.004346  1.010415
2019-09-26  1.002895  1.021855  1.009793
2019-09-27  1.001533  1.003061  1.012216
2019-09-28  0.998256  0.984714  1.009659
2019-09-29  1.020964  1.004581  1.005718


In [6]:
#也可以用一个 dict 来初始化
data_frame2 = pd.DataFrame({'A': 1.,
                      'B': pd.Timestamp('20130102'),
                      'C': pd.Series(1, index=list(range(4)), dtype='float32'),
                    'D': np.array([3] * 4, dtype='int32'),
                     'E': pd.Categorical(["test", "train", "test", "train"]),
                    'F': 'foo'})
print(data_frame2)
print(data_frame2.dtypes)

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo
A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object


In [7]:
data_frame2

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [8]:
x = np.array([[1,3,6.0,2],[2,3,4,5]])


In [9]:
#不同维度最大值
np.max(x, 0)

array([2., 3., 6., 5.])

查看前面几行也最后几行数据view the top and bottom rows of the frame:

In [10]:
data_frame.head()


A         B         C
2019-09-18  0.989936  0.990347  1.005533
2019-09-19  0.984528  0.980366  1.018356
2019-09-20  1.016322  1.003045  0.998361
2019-09-21  0.993233  0.993873  0.992124
2019-09-22  0.984321  0.998008  1.004511

In [11]:
data_frame2.tail(2)

A          B    C  D      E    F
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

显示索引、列和底层的 numpy 数据：

In [12]:
data_frame2.index

Int64Index([0, 1, 2, 3], dtype='int64')

In [13]:
data_frame2.columns

Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')

DataFrame.to_numpy（）给出了底层数据的NumPy表示。 请注意，当您的DataFrame具有不同数据类型的列时，这可能是一项昂贵的操作，

In [14]:
data_frame2.to_numpy()
#relatively expensive. with different data type

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

这归结为pandas和NumPy之间的根本区别：NumPy数组对整个数组有一个dtype，而pandas DataFrames每列有一个dtype。 当您调用DataFrame.to_numpy（）时，pandas将找到可以容纳DataFrame中所有dtypes的NumPy dtype。 这可能最终成为对象，这需要将每个值都转换为Python对象。 对于df，我们的所有浮点值的DataFrame，DataFrame.to_numpy（）都很快，不需要复制数据

In [15]:
data_frame2.values

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [16]:
data_frame.to_numpy()
#this is cheap, because floating-point value

array([[0.9899355 , 0.99034656, 1.00553281],
       [0.98452766, 0.98036606, 1.01835587],
       [1.01632168, 1.00304465, 0.99836147],
       [0.99323278, 0.99387331, 0.99212415],
       [0.98432102, 0.99800835, 1.00451057],
       [0.99407823, 0.98586923, 0.99093663],
       [0.99526502, 1.00994342, 1.00532531],
       [0.99767057, 1.00434615, 1.01041453],
       [1.00289541, 1.02185481, 1.00979347],
       [1.00153282, 1.00306054, 1.01221594],
       [0.99825626, 0.98471409, 1.00965897],
       [1.02096449, 1.00458091, 1.00571811]])

In [17]:
data_frame.T
#转置数据

2019-09-18  2019-09-19  2019-09-20  2019-09-21  2019-09-22  2019-09-23  \
A    0.989936    0.984528    1.016322    0.993233    0.984321    0.994078   
B    0.990347    0.980366    1.003045    0.993873    0.998008    0.985869   
C    1.005533    1.018356    0.998361    0.992124    1.004511    0.990937   

   2019-09-24  2019-09-25  2019-09-26  2019-09-27  2019-09-28  2019-09-29  
A    0.995265    0.997671    1.002895    1.001533    0.998256    1.020964  
B    1.009943    1.004346    1.021855    1.003061    0.984714    1.004581  
C    1.005325    1.010415    1.009793    1.012216    1.009659    1.005718

In [18]:
data_frame.T.values

array([[0.9899355 , 0.98452766, 1.01632168, 0.99323278, 0.98432102,
        0.99407823, 0.99526502, 0.99767057, 1.00289541, 1.00153282,
        0.99825626, 1.02096449],
       [0.99034656, 0.98036606, 1.00304465, 0.99387331, 0.99800835,
        0.98586923, 1.00994342, 1.00434615, 1.02185481, 1.00306054,
        0.98471409, 1.00458091],
       [1.00553281, 1.01835587, 0.99836147, 0.99212415, 1.00451057,
        0.99093663, 1.00532531, 1.01041453, 1.00979347, 1.01221594,
        1.00965897, 1.00571811]])

In [19]:
data_frame.describe()

A          B          C
count  12.000000  12.000000  12.000000
mean    0.998250   0.998334   1.005246
std     0.011193   0.011891   0.008048
min     0.984321   0.980366   0.990937
25%     0.992408   0.989227   1.002973
50%     0.996468   1.000527   1.005625
75%     1.001873   1.004405   1.009949
max     1.020964   1.021855   1.018356

In [20]:
data_frame.sort_index(axis = 0, ascending= False)

A         B         C
2019-09-29  1.020964  1.004581  1.005718
2019-09-28  0.998256  0.984714  1.009659
2019-09-27  1.001533  1.003061  1.012216
2019-09-26  1.002895  1.021855  1.009793
2019-09-25  0.997671  1.004346  1.010415
2019-09-24  0.995265  1.009943  1.005325
2019-09-23  0.994078  0.985869  0.990937
2019-09-22  0.984321  0.998008  1.004511
2019-09-21  0.993233  0.993873  0.992124
2019-09-20  1.016322  1.003045  0.998361
2019-09-19  0.984528  0.980366  1.018356
2019-09-18  0.989936  0.990347  1.005533

In [21]:
data_frame.sort_values(by = 'A',ascending = True)
#通过某一个特征维度进行排序

A         B         C
2019-09-22  0.984321  0.998008  1.004511
2019-09-19  0.984528  0.980366  1.018356
2019-09-18  0.989936  0.990347  1.005533
2019-09-21  0.993233  0.993873  0.992124
2019-09-23  0.994078  0.985869  0.990937
2019-09-24  0.995265  1.009943  1.005325
2019-09-25  0.997671  1.004346  1.010415
2019-09-28  0.998256  0.984714  1.009659
2019-09-27  1.001533  1.003061  1.012216
2019-09-26  1.002895  1.021855  1.009793
2019-09-20  1.016322  1.003045  0.998361
2019-09-29  1.020964  1.004581  1.005718

In [22]:
data_frame

A         B         C
2019-09-18  0.989936  0.990347  1.005533
2019-09-19  0.984528  0.980366  1.018356
2019-09-20  1.016322  1.003045  0.998361
2019-09-21  0.993233  0.993873  0.992124
2019-09-22  0.984321  0.998008  1.004511
2019-09-23  0.994078  0.985869  0.990937
2019-09-24  0.995265  1.009943  1.005325
2019-09-25  0.997671  1.004346  1.010415
2019-09-26  1.002895  1.021855  1.009793
2019-09-27  1.001533  1.003061  1.012216
2019-09-28  0.998256  0.984714  1.009659
2019-09-29  1.020964  1.004581  1.005718

## Selection

注意虽然用于选择和设置的标准Python / Numpy表达式非常直观并且对于交互式工作非常方便
就是对于data[start: end  : step] 这样的操作，不是很pandasnic， 这个库自有一套操作。

但对于生产代码，我们建议使用优化的pandas数据访问方法.at，.iat，.loc和.iloc。

In [23]:
data_frame[1:3]

A         B         C
2019-09-19  0.984528  0.980366  1.018356
2019-09-20  1.016322  1.003045  0.998361

In [24]:
data_frame[1:10:3]

A         B         C
2019-09-19  0.984528  0.980366  1.018356
2019-09-22  0.984321  0.998008  1.004511
2019-09-25  0.997671  1.004346  1.010415

In [25]:
#data_frame[1:5, 1:2]

#这样的pythonic的操作就不行了

data_frame.iloc[1:5, 1:2]

B
2019-09-19  0.980366
2019-09-20  1.003045
2019-09-21  0.993873
2019-09-22  0.998008

In [26]:
data_frame.iloc[1:5, -1]

2019-09-19    1.018356
2019-09-20    0.998361
2019-09-21    0.992124
2019-09-22    1.004511
Freq: D, Name: C, dtype: float64

In [27]:
data_frame['2019-09-19': '2019-09-21']

A         B         C
2019-09-19  0.984528  0.980366  1.018356
2019-09-20  1.016322  1.003045  0.998361
2019-09-21  0.993233  0.993873  0.992124

## Selection by labe

In [28]:
data_frame.loc[dates[0]]

A    0.989936
B    0.990347
C    1.005533
Name: 2019-09-18 00:00:00, dtype: float64

Selection by position

In [29]:
data_frame.iloc[1:5, -1]
#By integer slices, acting similar to numpy/python:

2019-09-19    1.018356
2019-09-20    0.998361
2019-09-21    0.992124
2019-09-22    1.004511
Freq: D, Name: C, dtype: float64

In [30]:
#By lists of integer position locations, similar to the numpy/python style:
data_frame.iloc[[1, 2, 4], [0, 2]]

A         C
2019-09-19  0.984528  1.018356
2019-09-20  1.016322  0.998361
2019-09-22  0.984321  1.004511

In [31]:
#For getting fast access to a scalar (equivalent to the prior method):
#相当于df.iloc[1, 1]
data_frame.iat[1,2]

1.0183558683515073

## by Boolean indexing

通过布尔 maks 来 索引

In [32]:
data_frame > 1

A      B      C
2019-09-18  False  False   True
2019-09-19  False  False   True
2019-09-20   True   True  False
2019-09-21  False  False  False
2019-09-22  False  False   True
2019-09-23  False  False  False
2019-09-24  False   True   True
2019-09-25  False   True   True
2019-09-26   True   True   True
2019-09-27   True   True   True
2019-09-28  False  False   True
2019-09-29   True   True   True

In [33]:
data_frame[data_frame > 1]

A         B         C
2019-09-18       NaN       NaN  1.005533
2019-09-19       NaN       NaN  1.018356
2019-09-20  1.016322  1.003045       NaN
2019-09-21       NaN       NaN       NaN
2019-09-22       NaN       NaN  1.004511
2019-09-23       NaN       NaN       NaN
2019-09-24       NaN  1.009943  1.005325
2019-09-25       NaN  1.004346  1.010415
2019-09-26  1.002895  1.021855  1.009793
2019-09-27  1.001533  1.003061  1.012216
2019-09-28       NaN       NaN  1.009659
2019-09-29  1.020964  1.004581  1.005718

In [34]:
data_frame.A > 1

2019-09-18    False
2019-09-19    False
2019-09-20     True
2019-09-21    False
2019-09-22    False
2019-09-23    False
2019-09-24    False
2019-09-25    False
2019-09-26     True
2019-09-27     True
2019-09-28    False
2019-09-29     True
Freq: D, Name: A, dtype: bool

In [35]:
data_frame[data_frame.A > 1]

A         B         C
2019-09-20  1.016322  1.003045  0.998361
2019-09-26  1.002895  1.021855  1.009793
2019-09-27  1.001533  1.003061  1.012216
2019-09-29  1.020964  1.004581  1.005718

## Setting 设置数值
赋值的方式 at loc iat iloc


In [36]:
s1 = pd.Series(list(range(0,12)), index = dates)

In [37]:
s1

2019-09-18     0
2019-09-19     1
2019-09-20     2
2019-09-21     3
2019-09-22     4
2019-09-23     5
2019-09-24     6
2019-09-25     7
2019-09-26     8
2019-09-27     9
2019-09-28    10
2019-09-29    11
Freq: D, dtype: int64

In [38]:
data_frame['F'] = s1
# setting new columns

In [39]:
data_frame

A         B         C   F
2019-09-18  0.989936  0.990347  1.005533   0
2019-09-19  0.984528  0.980366  1.018356   1
2019-09-20  1.016322  1.003045  0.998361   2
2019-09-21  0.993233  0.993873  0.992124   3
2019-09-22  0.984321  0.998008  1.004511   4
2019-09-23  0.994078  0.985869  0.990937   5
2019-09-24  0.995265  1.009943  1.005325   6
2019-09-25  0.997671  1.004346  1.010415   7
2019-09-26  1.002895  1.021855  1.009793   8
2019-09-27  1.001533  1.003061  1.012216   9
2019-09-28  0.998256  0.984714  1.009659  10
2019-09-29  1.020964  1.004581  1.005718  11

In [40]:
#data_frame.iat['F'][0] = np.nan
data_frame.iloc[0,-1] = None

Setting values by label:

```python
In [48]: df.at[dates[0], 'A'] = 0

Setting values by position:

In [49]: df.iat[0, 1] = 0
    或者是 iloc？

Setting by assigning with a NumPy array:

In [50]: df.loc[:, 'D'] = np.array([5] * len(df))
```

In [41]:
data_frame

A         B         C     F
2019-09-18  0.989936  0.990347  1.005533   NaN
2019-09-19  0.984528  0.980366  1.018356   1.0
2019-09-20  1.016322  1.003045  0.998361   2.0
2019-09-21  0.993233  0.993873  0.992124   3.0
2019-09-22  0.984321  0.998008  1.004511   4.0
2019-09-23  0.994078  0.985869  0.990937   5.0
2019-09-24  0.995265  1.009943  1.005325   6.0
2019-09-25  0.997671  1.004346  1.010415   7.0
2019-09-26  1.002895  1.021855  1.009793   8.0
2019-09-27  1.001533  1.003061  1.012216   9.0
2019-09-28  0.998256  0.984714  1.009659  10.0
2019-09-29  1.020964  1.004581  1.005718  11.0

# 丢失数据的处理，数据清洗
pandas主要使用值np.nan来表示缺失的数据。默认情况下，它不包含在计算中。

Missing Data section. https://pandas.pydata.org/pandas-docs/stable/user_guide/missing_data.html#missing-data

`reiindex`重建索引允许您更改/添加/删除指定轴上的索引。这将返回数据的副本。

In [42]:
df1 = data_frame.reindex(index=dates[0:4], columns=list(data_frame.columns) + ['E'])

In [43]:
df1.loc[0:4:2, 'E'] = 1
#loc at 可以lable index混用， iloc iat 只能纯index

In [44]:
df1
#上面的data frame 

A         B         C    F    E
2019-09-18  0.989936  0.990347  1.005533  NaN  1.0
2019-09-19  0.984528  0.980366  1.018356  1.0  NaN
2019-09-20  1.016322  1.003045  0.998361  2.0  1.0
2019-09-21  0.993233  0.993873  0.992124  3.0  NaN

In [45]:
df1.dropna(how='any')

A         B         C    F    E
2019-09-20  1.016322  1.003045  0.998361  2.0  1.0

In [46]:
df1.fillna(value=1.11)
#用 一个数值来填充 NAN值

A         B         C     F     E
2019-09-18  0.989936  0.990347  1.005533  1.11  1.00
2019-09-19  0.984528  0.980366  1.018356  1.00  1.11
2019-09-20  1.016322  1.003045  0.998361  2.00  1.00
2019-09-21  0.993233  0.993873  0.992124  3.00  1.11

In [47]:
pd.isna(df1)

A      B      C      F      E
2019-09-18  False  False  False   True  False
2019-09-19  False  False  False  False   True
2019-09-20  False  False  False  False  False
2019-09-21  False  False  False  False   True

## Stats 对数据进行统计分析


In [48]:
#求平均 不同维度
df1.mean(1)

2019-09-18    0.996454
2019-09-19    0.995812
2019-09-20    1.203546
2019-09-21    1.494808
Freq: D, dtype: float64

In [49]:
#求平均
df1.mean(0)

A    0.996004
B    0.991908
C    1.003594
F    2.000000
E    1.000000
dtype: float64

In [50]:
s = pd.Series([1, 3, 5, np.nan, 6, 8,3,1,3,2,1,3], index=dates).shift(2)

In [51]:
s

2019-09-18    NaN
2019-09-19    NaN
2019-09-20    1.0
2019-09-21    3.0
2019-09-22    5.0
2019-09-23    NaN
2019-09-24    6.0
2019-09-25    8.0
2019-09-26    3.0
2019-09-27    1.0
2019-09-28    3.0
2019-09-29    2.0
Freq: D, dtype: float64

In [52]:
data_frame

A         B         C     F
2019-09-18  0.989936  0.990347  1.005533   NaN
2019-09-19  0.984528  0.980366  1.018356   1.0
2019-09-20  1.016322  1.003045  0.998361   2.0
2019-09-21  0.993233  0.993873  0.992124   3.0
2019-09-22  0.984321  0.998008  1.004511   4.0
2019-09-23  0.994078  0.985869  0.990937   5.0
2019-09-24  0.995265  1.009943  1.005325   6.0
2019-09-25  0.997671  1.004346  1.010415   7.0
2019-09-26  1.002895  1.021855  1.009793   8.0
2019-09-27  1.001533  1.003061  1.012216   9.0
2019-09-28  0.998256  0.984714  1.009659  10.0
2019-09-29  1.020964  1.004581  1.005718  11.0

In [53]:
data_frame.sub(s, axis=0)
#自动的广播操作

A         B         C    F
2019-09-18       NaN       NaN       NaN  NaN
2019-09-19       NaN       NaN       NaN  NaN
2019-09-20  0.016322  0.003045 -0.001639  1.0
2019-09-21 -2.006767 -2.006127 -2.007876  0.0
2019-09-22 -4.015679 -4.001992 -3.995489 -1.0
2019-09-23       NaN       NaN       NaN  NaN
2019-09-24 -5.004735 -4.990057 -4.994675  0.0
2019-09-25 -7.002329 -6.995654 -6.989585 -1.0
2019-09-26 -1.997105 -1.978145 -1.990207  5.0
2019-09-27  0.001533  0.003061  0.012216  8.0
2019-09-28 -2.001744 -2.015286 -1.990341  7.0
2019-09-29 -0.979036 -0.995419 -0.994282  9.0

In [54]:
data_frame.max(1)

2019-09-18     1.005533
2019-09-19     1.018356
2019-09-20     2.000000
2019-09-21     3.000000
2019-09-22     4.000000
2019-09-23     5.000000
2019-09-24     6.000000
2019-09-25     7.000000
2019-09-26     8.000000
2019-09-27     9.000000
2019-09-28    10.000000
2019-09-29    11.000000
Freq: D, dtype: float64

In [55]:
data_frame.max(0)

A     1.020964
B     1.021855
C     1.018356
F    11.000000
dtype: float64

In [56]:
data_frame.min(0)

A    0.984321
B    0.980366
C    0.990937
F    1.000000
dtype: float64

In [57]:
data_frame.apply(lambda x: x.max() - x.min())

A     0.036643
B     0.041489
C     0.027419
F    10.000000
dtype: float64

In [58]:
data_frame.apply(lambda x: x.max() - x.min(), axis = 1)
#apply 默认每一列，也可以设置 axis = 1

2019-09-18    0.015597
2019-09-19    0.037990
2019-09-20    1.001639
2019-09-21    2.007876
2019-09-22    3.015679
2019-09-23    4.014131
2019-09-24    5.004735
2019-09-25    6.002329
2019-09-26    6.997105
2019-09-27    7.998467
2019-09-28    9.015286
2019-09-29    9.995419
Freq: D, dtype: float64

# Merge

pandas提供了各种工具，可以在连接/合并类型操作的情况下，轻松地将Series和DataFrame对象与索引和关系代数功能的各种设置逻辑组合在一起。

In [59]:
df = pd.DataFrame(np.random.randn(10, 4))

In [60]:
df

0         1         2         3
0  1.062130 -0.175628  0.159755  1.739656
1 -0.209627 -1.805313 -1.320563 -1.291183
2 -0.037564 -1.415054 -0.007676 -1.622740
3 -0.065259 -1.652177  0.620343  0.916965
4  0.359694  1.583328 -0.096927 -1.322966
5  1.552277 -1.226365  1.622037  0.859225
6  0.601195 -0.000273 -1.063575 -1.046511
7  0.417110  0.368958 -0.886600 -0.954898
8 -0.362485 -0.588403  0.450801  0.303764
9  1.352149 -0.688292 -1.264811  0.512458

In [61]:
#break it into pieces

pieces = [df[:3], df[3:7], df[7:]]

In [62]:
pieces[0]

0         1         2         3
0  1.062130 -0.175628  0.159755  1.739656
1 -0.209627 -1.805313 -1.320563 -1.291183
2 -0.037564 -1.415054 -0.007676 -1.622740

In [63]:
pd.concat(pieces)

0         1         2         3
0  1.062130 -0.175628  0.159755  1.739656
1 -0.209627 -1.805313 -1.320563 -1.291183
2 -0.037564 -1.415054 -0.007676 -1.622740
3 -0.065259 -1.652177  0.620343  0.916965
4  0.359694  1.583328 -0.096927 -1.322966
5  1.552277 -1.226365  1.622037  0.859225
6  0.601195 -0.000273 -1.063575 -1.046511
7  0.417110  0.368958 -0.886600 -0.954898
8 -0.362485 -0.588403  0.450801  0.303764
9  1.352149 -0.688292 -1.264811  0.512458

## SQL style Join

In [64]:
left = pd.DataFrame({'key': ['foo', 'foo'], 'lval': [1, 2]})

right = pd.DataFrame({'key': ['foo', 'foo'], 'rval': [4, 5]})

In [65]:
pd.merge(left, right, on='key')

key  lval  rval
0  foo     1     4
1  foo     1     5
2  foo     2     4
3  foo     2     5

In [66]:
left = pd.DataFrame({'key': ['foo', 'bar'], 'lval': [1, 2]})

right = pd.DataFrame({'key': ['foo', 'bar'], 'rval': [4, 5]})


In [67]:
pd.merge(left, right, on='key')

key  lval  rval
0  foo     1     4
1  bar     2     5

In [68]:
df = pd.DataFrame(np.random.randn(8, 4), columns=['A', 'B', 'C', 'D'])
s = df.loc[0]
df

A         B         C         D
0 -0.813085  0.488639 -0.395957 -2.817511
1  2.890615 -0.202613 -0.396441  1.116092
2  0.448051 -0.639552 -0.988499  0.451174
3 -0.360105  0.501142 -0.325823 -0.304948
4 -2.405415  0.285457 -1.072688  0.723796
5  0.246270 -2.138887  0.857017  0.292886
6  0.771561 -1.661360 -1.150699 -0.409972
7 -0.558314  1.311026  1.092720 -1.375962

In [69]:
df = df.append(s)

In [70]:
df

A         B         C         D
0 -0.813085  0.488639 -0.395957 -2.817511
1  2.890615 -0.202613 -0.396441  1.116092
2  0.448051 -0.639552 -0.988499  0.451174
3 -0.360105  0.501142 -0.325823 -0.304948
4 -2.405415  0.285457 -1.072688  0.723796
5  0.246270 -2.138887  0.857017  0.292886
6  0.771561 -1.661360 -1.150699 -0.409972
7 -0.558314  1.311026  1.092720 -1.375962
0 -0.813085  0.488639 -0.395957 -2.817511

In [71]:
df.iloc[-1]

A   -0.813085
B    0.488639
C   -0.395957
D   -2.817511
Name: 0, dtype: float64

In [72]:
## Grouping

In [73]:
df = pd.DataFrame({'A': ['foo', 'bar', 'foo', 'bar',
     'foo', 'bar', 'foo', 'foo'],
                'B': ['one', 'one', 'two', 'three',
                        'two', 'two', 'one', 'three'],
               'C': np.random.randn(8),
                 'D': np.random.randn(8)})


In [74]:
df.groupby('A').sum()

C        D
A                     
bar  2.381716 -0.87077
foo -2.660868  1.62528

In [75]:
df.groupby(['A', 'B']).sum()

C         D
A   B                        
bar one    1.560562  0.650416
    three  1.805622 -0.237838
    two   -0.984468 -1.283348
foo one    1.437385  2.131087
    three -0.704039 -0.383192
    two   -3.394215 -0.122615

# Time series
pandas has simple, powerful, and efficient functionality for performing resampling operations during frequency conversion (e.g., converting secondly data into 5-minutely data). This is extremely common in, but not limited to, financial applications. See the Time Series section.https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#timeseries

In [76]:
rng = pd.date_range('1/1/2012', periods=100, freq='S')

In [77]:
rng

DatetimeIndex(['2012-01-01 00:00:00', '2012-01-01 00:00:01',
               '2012-01-01 00:00:02', '2012-01-01 00:00:03',
               '2012-01-01 00:00:04', '2012-01-01 00:00:05',
               '2012-01-01 00:00:06', '2012-01-01 00:00:07',
               '2012-01-01 00:00:08', '2012-01-01 00:00:09',
               '2012-01-01 00:00:10', '2012-01-01 00:00:11',
               '2012-01-01 00:00:12', '2012-01-01 00:00:13',
               '2012-01-01 00:00:14', '2012-01-01 00:00:15',
               '2012-01-01 00:00:16', '2012-01-01 00:00:17',
               '2012-01-01 00:00:18', '2012-01-01 00:00:19',
               '2012-01-01 00:00:20', '2012-01-01 00:00:21',
               '2012-01-01 00:00:22', '2012-01-01 00:00:23',
               '2012-01-01 00:00:24', '2012-01-01 00:00:25',
               '2012-01-01 00:00:26', '2012-01-01 00:00:27',
               '2012-01-01 00:00:28', '2012-01-01 00:00:29',
               '2012-01-01 00:00:30', '2012-01-01 00:00:31',
               '2012-01-

In [78]:
ts = pd.Series(np.random.randint(0, 500, len(rng)), index=rng)

In [79]:
ts.shape

(100,)

In [80]:
ts.resample('1Min').sum()
# 把时间统计的数据，变成 另一个时间段内统计的数据


2012-01-01 00:00:00    15990
2012-01-01 00:01:00     9369
Freq: T, dtype: int32

# Ploting


In [81]:
# 化曲线图
ts = pd.Series(np.random.randn(1000), index = list(range(1000)))
ts = ts.cumsum()
print(ts.shape)

(1000,)


In [82]:
ts.plot()