# 读写`Tensor`

我们可以直接使用`save`函数和`load`函数分别存储和读取`Tensor`。`save`使用Python的pickle实用程序将对象进行序列化，然后将序列化的对象保存到disk，使用`save`可以保存各种对象,包括模型、张量和字典等。而`laod`使用pickle unpickle工具将pickle的对象文件反序列化为内存。

In [1]:
import torch
import torch.nn as nn

import sys
sys.path.append("..") 

x = torch.ones(10,10)
torch.save(x, 'torch_tensor.pt')

In [2]:
x2 = torch.load('torch_tensor.pt')

In [3]:
print(x2)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


## 保存多个数值

In [4]:
y = torch.randn(10,3)
print(y)

tensor([[ 1.4742, -0.2547, -0.3533],
        [ 0.5403, -0.4703, -0.7321],
        [ 0.9841,  1.2643, -0.1577],
        [ 1.2402,  0.4635,  0.5740],
        [-1.1961, -1.0300,  0.1861],
        [-0.4376, -0.2366,  0.9359],
        [-0.3981,  1.8926,  0.2100],
        [ 0.0125, -0.6135, -0.3395],
        [ 0.8022,  0.1154,  0.0717],
        [ 0.7155,  0.8362,  0.1046]])


## 保存 tensor list

In [5]:
torch.save([x2,y], 'torch_tensor.pt')
tensor_list = torch.load('torch_tensor.pt')
print(tensor_list)

[tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]), tensor([[ 1.4742, -0.2547, -0.3533],
        [ 0.5403, -0.4703, -0.7321],
        [ 0.9841,  1.2643, -0.1577],
        [ 1.2402,  0.4635,  0.5740],
        [-1.1961, -1.0300,  0.1861],
        [-0.4376, -0.2366,  0.9359],
        [-0.3981,  1.8926,  0.2100],
        [ 0.0125, -0.6135, -0.3395],
        [ 0.8022,  0.1154,  0.0717],
        [ 0.7155,  0.8362,  0.1046]])]


## 保存 tensor dict

In [6]:
torch.save({'x': x2, 'y': y}, 'xy_dict.pt')
xy = torch.load('xy_dict.pt')
xy

{'x': tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
 'y': tensor([[ 1.4742, -0.2547, -0.3533],
         [ 0.5403, -0.4703, -0.7321],
         [ 0.9841,  1.2643, -0.1577],
         [ 1.2402,  0.4635,  0.5740],
         [-1.1961, -1.0300,  0.1861],
         [-0.4376, -0.2366,  0.9359],
         [-0.3981,  1.8926,  0.2100],
         [ 0.0125, -0.6135, -0.3395],
         [ 0.8022,  0.1154,  0.0717],
         [ 0.7155,  0.8362,  0.1046]])}

# 读写模型 保存读取Models 两种方式，保存参数数据，直接保存整个模型，包括结构。

## State_dict
在PyTorch中，`Module`的可学习参数(即权重和偏差)，模块模型包含在参数中(通过`model.parameters()`访问)。`state_dict`是一个从参数名称隐射到参数`Tesnor`的字典对象。

In [7]:
net = nn.Sequential(nn.Linear(16,8), nn.Linear(8,4), nn.Linear(4,1))
print(net)

Sequential(
  (0): Linear(in_features=16, out_features=8, bias=True)
  (1): Linear(in_features=8, out_features=4, bias=True)
  (2): Linear(in_features=4, out_features=1, bias=True)
)


In [8]:
print(net.state_dict())
x = torch.randn(10,16)
out = net(x)
print(out)

OrderedDict([('0.weight', tensor([[ 0.2331,  0.0276, -0.2451,  0.0109,  0.1566, -0.2014, -0.2156, -0.1280,
          0.2056,  0.1407,  0.1083,  0.1882,  0.0551, -0.0400,  0.0443, -0.2372],
        [ 0.1692,  0.1618, -0.0517, -0.0812, -0.1555, -0.0163,  0.0334,  0.2266,
         -0.2469, -0.1984, -0.1384, -0.0199,  0.0136, -0.1724, -0.1590, -0.0053],
        [-0.0704,  0.2221, -0.2207,  0.1495, -0.2040,  0.2320,  0.1979, -0.1726,
          0.1717,  0.2442, -0.0479,  0.1695, -0.1683,  0.0465,  0.1016, -0.1294],
        [-0.1667, -0.0417,  0.0753,  0.2427,  0.1194,  0.0642, -0.0650,  0.1371,
         -0.0284,  0.1100,  0.1789,  0.0374,  0.1587, -0.0658,  0.2488,  0.0230],
        [-0.0024, -0.1640, -0.0913, -0.0604,  0.0315,  0.1788, -0.0572,  0.2402,
         -0.1028,  0.2186,  0.0836, -0.1235, -0.0566,  0.2199,  0.1654, -0.0090],
        [-0.0714, -0.0216,  0.1099,  0.1452, -0.2453,  0.0840,  0.0402,  0.1697,
         -0.1719,  0.2065, -0.1270, -0.1910, -0.1444,  0.1259, -0.0575,  0.142

注意，只有具有可学习参数的层(卷积层、线性层等)才有`state_dict`中的条目。优化器(`optim`)也有一个`state_dict`，其中包含关于优化器状态以及所使用的超参数的信息。

```python
optimizer = torch.optim.SGD(net.parameters(), lr=0.001, momentum=0.9)
optimizer.state_dict()
```

输出：

In [9]:
optimizer = torch.optim.SGD(net.parameters(), lr=0.001, momentum=0.9)
print(optimizer.state_dict())

{'state': {}, 'param_groups': [{'lr': 0.001, 'momentum': 0.9, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'params': [2276782719624, 2276782808664, 2276782808736, 2276782808808, 2276782808880, 2276782808952]}]}


##  保存和加载模型

PyTorch中保存和加载训练模型有两种常见的方法:

1. 仅保存和加载模型参数(`state_dict`)；
2. 保存和加载整个模型。

### 1. 保存和加载`state_dict`(推荐方式)

In [10]:
torch.save(net.state_dict(), 'linear_net_state_dict.pt')

In [11]:
net2 = nn.Sequential(nn.Linear(16,8), nn.Linear(8,4), nn.Linear(4,1))
net2.load_state_dict(torch.load('linear_net_state_dict.pt'))
print(net2(x))

tensor([[-0.4595],
        [-0.3870],
        [-0.3978],
        [-0.3469],
        [-0.6094],
        [-0.3387],
        [-0.4820],
        [-0.5118],
        [-0.6691],
        [-0.5440]], grad_fn=<AddmmBackward>)


## 2. 保存和加载整个模型

这种方式应该是模型的结构，梯度等数据也都保存了。

In [12]:
torch.save(net2, 'linear_net_model.pt')

#载入pt文件就载入了整个网络
model = torch.load('linear_net_model.pt')
print(model(x))

tensor([[-0.4595],
        [-0.3870],
        [-0.3978],
        [-0.3469],
        [-0.6094],
        [-0.3387],
        [-0.4820],
        [-0.5118],
        [-0.6691],
        [-0.5440]], grad_fn=<AddmmBackward>)


因为这`net`和`net2`都有同样的模型参数，那么对同一个输入`X`的计算结果将会是一样的。上面的输出也验证了这一点。

此外，还有一些其他使用场景，例如GPU与CPU之间的模型保存与读取、使用多块GPU的模型的存储等等，使用的时候可以参考[官方文档](https://pytorch.org/tutorials/beginner/saving_loading_models.html)。

## 小结

- 通过`save`函数和`load`函数可以很方便地读写`Tensor`。
- 通过`save`函数和`load_state_dict`函数可以很方便地读写模型的参数。