In [1]:
import torch
import sys
sys.path.append("..") 

# 关于GPU 的操作

In [2]:
torch.cuda.is_available()

True

In [3]:
torch.cuda.device_count() # 输出 1

1

In [4]:
torch.cuda.current_device() # 输出 0

0

In [5]:
torch.cuda.get_device_name(0) 

'GeForce GTX 1070'

In [6]:
data = torch.randn(5,3)

In [7]:
data

tensor([[ 0.2283, -1.2424, -0.5177],
        [-1.4326, -0.1590,  1.4204],
        [ 0.6056,  0.9192,  0.8137],
        [ 0.0744, -0.8080, -0.7335],
        [ 1.8019, -0.5622,  1.9080]])

In [8]:
data.cuda(0)

tensor([[ 0.2283, -1.2424, -0.5177],
        [-1.4326, -0.1590,  1.4204],
        [ 0.6056,  0.9192,  0.8137],
        [ 0.0744, -0.8080, -0.7335],
        [ 1.8019, -0.5622,  1.9080]], device='cuda:0')

使用`.cuda()`可以将CPU上的`Tensor`转换（复制）到GPU上。如果有多块GPU，我们用`.cuda(i)`来表示第 $i$ 块GPU及相应的显存（$i$从0开始）且`cuda(0)`和`cuda()`等价。

In [9]:
data = data.cuda(0)

In [10]:
data 

tensor([[ 0.2283, -1.2424, -0.5177],
        [-1.4326, -0.1590,  1.4204],
        [ 0.6056,  0.9192,  0.8137],
        [ 0.0744, -0.8080, -0.7335],
        [ 1.8019, -0.5622,  1.9080]], device='cuda:0')

In [11]:
data.device

device(type='cuda', index=0)

需要注意的是，存储在不同位置中的数据是不可以直接进行计算的。即存放在CPU上的数据不可以直接与存放在GPU上的数据进行运算，位于不同GPU上的数据也是不能直接进行计算的。

In [12]:
data2 = torch.randn(1,3)
print(data+data2)
    


RuntimeError: expected backend CUDA and dtype Float but got backend CPU and dtype Float

In [13]:
print(data.cpu()+data2)

tensor([[-1.4651, -3.3751, -1.5150],
        [-3.1260, -2.2917,  0.4231],
        [-1.0878, -1.2136, -0.1837],
        [-1.6189, -2.9407, -1.7308],
        [ 0.1086, -2.6950,  0.9107]])


## 模型的GPU计算

同`Tensor`类似，PyTorch模型也可以通过`.cuda`转换到GPU上。我们可以通过检查模型的参数的`device`属性来查看存放模型的设备。

In [14]:

net = torch.nn.Sequential(torch.nn.Linear(3,5), torch.nn.Linear(5,1))
net.to('cuda')

Sequential(
  (0): Linear(in_features=3, out_features=5, bias=True)
  (1): Linear(in_features=5, out_features=1, bias=True)
)

同`Tensor`类似，PyTorch模型也可以通过`.cuda`转换到GPU上。我们可以通过检查模型的参数的`device`属性来查看存放模型的设备。

In [15]:
net(data)

tensor([[ 0.1380],
        [-0.3661],
        [-0.0569],
        [ 0.1159],
        [ 0.0797]], device='cuda:0', grad_fn=<AddmmBackward>)

In [16]:
list(net[0].parameters())[0].device

device(type='cuda', index=0)