## 配置
安装jupyter notebook、pytoch、matplotlib等包
## 基本数据操作
Tensor， 基本和numpy数组差不多，和matlab里一些操作也很像

In [1]:
import torch
#创建tensor
x = torch.empty((5,2))
print(x)

tensor([[1.0286e-38, 9.0919e-39],
        [8.9082e-39, 9.2755e-39],
        [8.4490e-39, 1.0194e-38],
        [9.0919e-39, 8.4490e-39],
        [1.0745e-38, 1.0561e-38]])

In [2]:
#随机建立一个tensor 范围0-1
x = torch.rand((5,3))
print(x)

tensor([[0.1221, 0.0389, 0.0697],
        [0.8840, 0.0451, 0.5212],
        [0.0193, 0.8137, 0.1887],
        [0.3860, 0.2646, 0.7590],
        [0.2598, 0.3354, 0.8827]])


In [3]:
#符合标准正态分布的随机建立
torch.randn((5,4))

tensor([[ 0.9272, -1.1415, -1.9746, -0.8791],
        [-1.0584, -0.5484,  0.0530, -1.1074],
        [-1.2382, -1.9759, -0.0450,  1.6494],
        [ 0.5545,  0.3283,  0.0760,  0.2881],
        [ 0.4399, -0.3384,  0.6106, -0.5153]])

In [5]:
torch.linspace(1,10,steps=10)
#线性地创建tensor

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [8]:
torch.normal(torch.arange(1,5, dtype = torch.float64), torch.arange(1,5, dtype = torch.float64))
#离散正态分布 这个用途存疑，没遇到过

tensor([ 1.0642,  6.2892, -0.5409,  5.7580], dtype=torch.float64)

In [20]:
#从列表中建立
import numpy as np
data = np.random.rand(5,2)
x = torch.tensor([3.0,1,3,4])
y = torch.from_numpy(data)
z = y.numpy()
print('x : {} type : {}\ny : {} type : {}\nz : {} type : {}\n '.format(x,type(x),y,type(y),z,type(z)))

x : tensor([3., 1., 3., 4.]) type : <class 'torch.Tensor'>
y : tensor([[0.6175, 0.7324],
        [0.0112, 0.2388],
        [0.5185, 0.9236],
        [0.8491, 0.0439],
        [0.7135, 0.6283]], dtype=torch.float64) type : <class 'torch.Tensor'>
z : [[0.61754746 0.73241525]
 [0.01122493 0.23879336]
 [0.51853918 0.92358194]
 [0.84911759 0.04394372]
 [0.7135324  0.62829926]] type : <class 'numpy.ndarray'>
 


In [21]:
#其他地建立方式
x = x.new_ones(5, 3, dtype=torch.float64)  # 返回的tensor默认具有相同的torch.dtype和torch.device
print(x)

x = torch.randn_like(x, dtype=torch.float) # 指定新的数据类型
print(x) 

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.5843, -0.2085, -0.0090],
        [-0.1026, -0.5490,  0.0836],
        [ 0.8599, -0.1260,  0.3729],
        [-0.1219, -0.2635, -0.6295],
        [-0.4779, -0.7205,  0.3781]])


In [22]:
#获取tensor的形状
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


Torch Tensor的基础操作

|               函数                |           功能            |
| :-------------------------------: | :-----------------------: |
|          Tensor(*sizes)           |       基础构造函数        |
|           tensor(data,)           |  类似np.array的构造函数   |
|           ones(*sizes)            |         全1Tensor         |
|           zeros(*sizes)           |         全0Tensor         |
|            eye(*sizes)            |    对角线为1，其他为0     |
|          arange(s,e,step          |    从s到e，步长为step     |
|        linspace(s,e,steps)        | 从s到e，均匀切分成steps份 |
|        rand/randn(*sizes)         |       均匀/标准分布       |
| normal(mean,std)/uniform(from,to) |     正态分布/均匀分布     |
|            randperm(m)            |         随机排列          |



这里出现了一个dtype（data type 数据类型嘛）参数，那么pytorch里数据类型有哪些呢？
![imgs/datatype.jpg](attachment:imgs/datatype.jpg)

## 算术操作
加减乘，比较常见

In [23]:
y = torch.randn(5,3)
x+y

tensor([[-0.7977, -0.3612, -0.7910],
        [-2.0437, -0.0728,  1.2005],
        [ 1.9359,  0.1579, -0.1358],
        [-0.2157, -1.1487, -2.5557],
        [-1.4501, -0.0460,  1.0075]])

In [25]:
torch.add(x,y)

tensor([[-0.7977, -0.3612, -0.7910],
        [-2.0437, -0.0728,  1.2005],
        [ 1.9359,  0.1579, -0.1358],
        [-0.2157, -1.1487, -2.5557],
        [-1.4501, -0.0460,  1.0075]])

In [26]:
# inplace 操作 ，就地操作，直接修改y，而不是返回一个新的值
# 不需要 y = y.add(x)
y.add_(x)
print(y)

tensor([[-0.7977, -0.3612, -0.7910],
        [-2.0437, -0.0728,  1.2005],
        [ 1.9359,  0.1579, -0.1358],
        [-0.2157, -1.1487, -2.5557],
        [-1.4501, -0.0460,  1.0075]])


## 索引
我们还可以使用类似NumPy的索引操作来访问`Tensor`的一部分，需要注意的是：**索引出来的结果与原数据共享内存，也即修改一个，另一个会跟着修改。** 
索引操作在python  里，是直接对对象进行操作

In [29]:
y = x[0,:]
y += 1
print(x)

# 严格说是切片索引是直接操作原始数据，而普通的索引就是简单的 赋值。
y = x[0,0]
print('before : {}'.format(y))
y = 100
print('after {}'.format(y))
print(x)

tensor([[ 2.4157,  2.7915,  2.9910],
        [-0.1026, -0.5490,  0.0836],
        [ 0.8599, -0.1260,  0.3729],
        [-0.1219, -0.2635, -0.6295],
        [-0.4779, -0.7205,  0.3781]])
before : 2.4157216548919678
after 100
tensor([[ 2.4157,  2.7915,  2.9910],
        [-0.1026, -0.5490,  0.0836],
        [ 0.8599, -0.1260,  0.3729],
        [-0.1219, -0.2635, -0.6295],
        [-0.4779, -0.7205,  0.3781]])


|              函数               |                         功能                          |
| :-----------------------------: | :---------------------------------------------------: |
| index_select(input, dim, index) |      在指定维度dim上选取，比如选取某些行、某些列      |
|   masked_select(input, mask)    |       例子如上，a[a>0]，使用ByteTensor进行选取        |
|         non_zero(input)         |                     非0元素的下标                     |
|    gather(input, dim, index)    | 根据index，在dim维度上选取数据，输出的size与index一样 |

除了常用的索引选择数据之外，PyTorch还提供了一些高级的选择函数:

mask操作可以这样做

In [67]:
#按照size构造tensor 大写
x = torch.Tensor(3,3)
print(x)

#随机初始一个
x = torch.randn(3,3)
print(x)
print(x < 0.5)

#取出符合要求的元素
print(x[x<0.5])
print(torch.masked_select(x, x < 0.5))

#这里需要对类型进行转换
mask = x<0.5
try:
    #直接做会出错，先类型转换一下
    print(x * mask)
finally:
    print(mask.type(torch.float64))
    print(mask.float())
    print(mask.type_as(x))
    print(x*mask.float())
    
    print('上面三种方法都一样')

    w = np.random.rand(5,3)
    print(w)
    list_mask=np.random.rand(*w.shape) < 0.5
    print((list_mask))
    #注意两种mask 方式的不一样
    print(w[list_mask])
    print(w * list_mask)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[ 1.1835,  0.4402, -1.7738],
        [ 1.2606, -0.8378,  0.0348],
        [-0.8016,  0.9382,  0.1095]])
tensor([[0, 1, 1],
        [0, 1, 1],
        [1, 0, 1]], dtype=torch.uint8)
tensor([ 0.4402, -1.7738, -0.8378,  0.0348, -0.8016,  0.1095])
tensor([ 0.4402, -1.7738, -0.8378,  0.0348, -0.8016,  0.1095])
tensor([[0., 1., 1.],
        [0., 1., 1.],
        [1., 0., 1.]], dtype=torch.float64)
tensor([[0., 1., 1.],
        [0., 1., 1.],
        [1., 0., 1.]])
tensor([[0., 1., 1.],
        [0., 1., 1.],
        [1., 0., 1.]])
tensor([[ 0.0000,  0.4402, -1.7738],
        [ 0.0000, -0.8378,  0.0348],
        [-0.8016,  0.0000,  0.1095]])
上面三种方法都一样
[[0.87520726 0.84689209 0.84645978]
 [0.43877319 0.22121679 0.77170276]
 [0.72807338 0.21030772 0.61317052]
 [0.34889811 0.41063939 0.80024706]
 [0.82906917 0.43560517 0.4836327 ]]
[[False False  True]
 [False False False]
 [ True  True  True]
 [ True  True  True]
 [False  

RuntimeError: expected backend CPU and dtype Float but got backend CPU and dtype Byte

## 改变形状
用`view()`来改变`Tensor`的形状：

In [80]:
x = torch.randn(3,3)
print(x)
y = x.view(-1,9)
print(y)
y[0][0] = 666
print(y)
print(x)
print(x.view(y.shape) == y)

tensor([[-0.5498,  1.7367, -0.6230],
        [ 0.9497, -0.8038,  0.7044],
        [-0.1894, -0.4409, -0.7654]])
tensor([[-0.5498,  1.7367, -0.6230,  0.9497, -0.8038,  0.7044, -0.1894, -0.4409,
         -0.7654]])
tensor([[ 6.6600e+02,  1.7367e+00, -6.2303e-01,  9.4971e-01, -8.0376e-01,
          7.0442e-01, -1.8935e-01, -4.4093e-01, -7.6543e-01]])
tensor([[ 6.6600e+02,  1.7367e+00, -6.2303e-01],
        [ 9.4971e-01, -8.0376e-01,  7.0442e-01],
        [-1.8935e-01, -4.4093e-01, -7.6543e-01]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=torch.uint8)


**注意`view()`返回的新tensor与源tensor共享内存（其实是同一个tensor），也即更改其中的一个，另外一个也会跟着改变。(顾名思义，view仅仅是改变了对这个张量的观察角度)**

使用`clone`还有一个好处是会被记录在计算图中，即梯度回传到副本时也会传到源`Tensor`。

In [81]:
y2 = x.reshape(-1,9)
#但是此函数并不能保证返回的是其拷贝
#不推荐使用reshape函数
print(y2)
y2[0][0] = 888
print(y2)
print(x)

x = torch.randn(3,3)
print(x)
#clone() 返回副本 然后再view
y3 = x.clone().view(-1,9)
y3[0][0] = 777
print(y3)
print(x)

tensor([[ 6.6600e+02,  1.7367e+00, -6.2303e-01,  9.4971e-01, -8.0376e-01,
          7.0442e-01, -1.8935e-01, -4.4093e-01, -7.6543e-01]])
tensor([[ 8.8800e+02,  1.7367e+00, -6.2303e-01,  9.4971e-01, -8.0376e-01,
          7.0442e-01, -1.8935e-01, -4.4093e-01, -7.6543e-01]])
tensor([[ 8.8800e+02,  1.7367e+00, -6.2303e-01],
        [ 9.4971e-01, -8.0376e-01,  7.0442e-01],
        [-1.8935e-01, -4.4093e-01, -7.6543e-01]])
tensor([[ 0.0558,  0.2770, -0.3539],
        [-1.0539, -0.9913, -0.0664],
        [-0.4048,  1.1260,  0.1387]])
tensor([[ 7.7700e+02,  2.7697e-01, -3.5393e-01, -1.0539e+00, -9.9126e-01,
         -6.6355e-02, -4.0477e-01,  1.1260e+00,  1.3871e-01]])
tensor([[ 0.0558,  0.2770, -0.3539],
        [-1.0539, -0.9913, -0.0664],
        [-0.4048,  1.1260,  0.1387]])


另外一个常用的函数就是`item()`, 它可以将一个标量`Tensor`转换成一个Python number：

In [82]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.0626])
0.06256353855133057


## 线性代数运算
PyTorch还支持一些线性函数，这里提一下，免得用起来的时候自己造轮子，具体用法参考官方文档。
PyTorch中的`Tensor`支持超过一百种操作，包括转置、索引、切片、数学运算、线性代数、随机数等等，可参考[官方文档](https://pytorch.org/docs/stable/tensors.html)。

|               函数               |               功能                |
| :------------------------------: | :-------------------------------: |
|              trace               |     对角线元素之和(矩阵的迹)      |
|               diag               |            对角线元素             |
|            triu/tril             | 矩阵的上三角/下三角，可指定偏移量 |
|              mm/bmm              |     矩阵乘法，batch的矩阵乘法     |
| addmm/addbmm/addmv/addr/badbmm.. |             矩阵运算              |
|                t                 |               转置                |
|            dot/cross             |             内积/外积             |
|             inverse              |             求逆矩阵              |
|               svd                |            奇异值分解             |

##  广播机制 Broadcast
前面我们看到如何对两个形状相同的`Tensor`做按元素运算。当对两个形状不同的`Tensor`按元素运算时，可能会触发广播（broadcasting）机制：先适当复制元素使这两个`Tensor`形状相同后再按元素运算。例如：

In [97]:
x = torch.randn(5,3)
y = torch.randn(3)

#注意， 要维度相同呢
print(x.add(y))

#或者双方都有一个维度为1：
x = torch.arange(1,3).view(2,1)
y = torch.arange(1,4).view(1,3)
print(x,y)
print(y.add(x))

#inplace 操作不会触发 broadcast操作

#不同会怎么样
x = torch.randn(5,3)
y = torch.randn(4)
x.add(y)
    

tensor([[-0.5271,  0.8905,  0.9801],
        [-2.2593,  1.1630, -2.1686],
        [-2.1433, -1.8415, -0.1482],
        [-0.7257,  0.1922, -1.0287],
        [-0.5688,  0.5115, -3.8828]])
tensor([[1],
        [2]]) tensor([[1, 2, 3]])
tensor([[2, 3, 4],
        [3, 4, 5]])


RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 1

## 2.2.4 运算的内存开销

前面说了，索引、`view`是不会开辟新内存的，而像`y = x + y`这样的运算是会新开内存的，然后将`y`指向新内存。为了演示这一点，我们可以使用Python自带的`id`函数：如果两个实例的ID一致，那么它们所对应的内存地址相同；反之则不同。

```python
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y = y + x
print(id(y) == id_before) # False 
```

如果想指定结果到原来的`y`的内存，我们可以使用前面介绍的索引来进行替换操作。在下面的例子中，我们把`x + y`的结果通过`[:]`写进`y`对应的内存中。

```python
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y[:] = y + x
print(id(y) == id_before) # True
```

我们还可以使用运算符全名函数中的`out`参数或者自加运算符`+=`(也即`add_()`)达到上述效果，例如`torch.add(x, y, out=y)`和`y += x`(`y.add_(x)`

x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
torch.add(x, y, out=y) # y += x, y.add_(x)
print(id(y) == id_before) # True

## 2.2.5 `Tensor`和NumPy相互转换

我们很容易用`numpy()`和`from_numpy()`将`Tensor`和NumPy中的数组相互转换。但是需要注意的一点是：
**这两个函数所产生的的`Tensor`和NumPy中的数组共享相同的内存（所以他们之间的转换很快），改变其中一个时另一个也会改变！！！**

> 还有一个常用的将NumPy中的array转换成`Tensor`的方法就是`torch.tensor()`, 需要注意的是，此方法总是会进行数据拷贝（就会消耗更多的时间和空间），所以返回的`Tensor`和原来的数据不再共享内存。

In [102]:
import numpy as np
x = np.random.randn(3,3)
print(x)
x_tensor = torch.from_numpy(x)
x_tensor[0] = 1
print(x_tensor, x)

x = torch.randn(3,3)
print(x)
x_np = x.numpy()
x_np[0] = 222
print(x_np, x)

[[ 0.94481227  0.08396565  0.48694674]
 [-0.80725734  0.51887894 -2.26874429]
 [-0.07192007  0.0992277  -0.05335085]]
tensor([[ 1.0000,  1.0000,  1.0000],
        [-0.8073,  0.5189, -2.2687],
        [-0.0719,  0.0992, -0.0534]], dtype=torch.float64) [[ 1.          1.          1.        ]
 [-0.80725734  0.51887894 -2.26874429]
 [-0.07192007  0.0992277  -0.05335085]]
tensor([[ 0.4332,  0.0149, -0.3476],
        [-1.1909, -0.7243,  2.1325],
        [-0.4085,  0.3653, -0.2600]])
[[222.         222.         222.        ]
 [ -1.1908967   -0.7243283    2.1325471 ]
 [ -0.40848246   0.3652671   -0.26003286]] tensor([[222.0000, 222.0000, 222.0000],
        [ -1.1909,  -0.7243,   2.1325],
        [ -0.4085,   0.3653,  -0.2600]])


# 特别提醒[注意Tensor大小写]

最重要的区别t.Tensor和t.tensor：不论输入的类型是什么，`t.tensor()`都会进行数据拷贝，不会共享内存；`t.Tensor()`与`Numpy`共享内存，但当Numpy的数据类型和Tensor的类型不一样的时候，数据会被复制，不会共享内存。
可使用`t.from_numpy()` 或者 `t.detach()` 将Numpy转为Tensor，与原Numpy数据共享内存。
附上实验证明
常规转换：使用`t.from_numpy()` 将Numpy转为Tensor，使用 `torch.numpy()` 将Tensor转为Numpy
这里两种方式都是共享内存

所有在CPU上的`Tensor`（除了`CharTensor`）都支持与NumPy数组相互转换。

此外上面提到还有一个常用的方法就是直接用`torch.tensor()`将NumPy数组转换成`Tensor`，需要注意的是该方法总是会进行数据拷贝，返回的`Tensor`和原来的数据不再共享内存。

In [103]:
x = np.random.randn(3,3)
print(x)
x_np = torch.tensor(x)
x_np[0] = 222
print(x_np, x)

[[-0.34780906  0.32796017  1.58553259]
 [-0.0211887   0.41080688 -0.99407921]
 [ 0.53120997 -0.5750506   0.7851364 ]]
tensor([[ 2.2200e+02,  2.2200e+02,  2.2200e+02],
        [-2.1189e-02,  4.1081e-01, -9.9408e-01],
        [ 5.3121e-01, -5.7505e-01,  7.8514e-01]], dtype=torch.float64) [[-0.34780906  0.32796017  1.58553259]
 [-0.0211887   0.41080688 -0.99407921]
 [ 0.53120997 -0.5750506   0.7851364 ]]


## 2.2.6 `Tensor` on GPU

用方法`to()`可以将`Tensor`在CPU和GPU（需要硬件支持）之间相互移动。

In [112]:
# 以下代码只有在PyTorch GPU版本上才会执行
x = torch.randn(5,5)
if torch.cuda.is_available():
    device = torch.device("cuda")          # GPU
    y = torch.ones_like(x, device = device)  # 直接创建一个在GPU上的Tensor

    x = x.to(device)                       # 等价于 .to("cuda")
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # to()还可以同时更改数据类型

tensor([[ 2.2606,  1.4849, -1.2709,  0.4529,  1.6387],
        [ 0.3824,  1.8151, -0.0333, -0.8842,  2.2383],
        [ 0.9259,  0.8722, -0.0529,  0.6273, -0.1627],
        [ 3.8030,  1.4720,  1.3928,  0.3691,  1.4324],
        [ 0.7160,  3.1162,  0.8997,  1.8662,  1.2300]], device='cuda:0')
tensor([[ 2.2606,  1.4849, -1.2709,  0.4529,  1.6387],
        [ 0.3824,  1.8151, -0.0333, -0.8842,  2.2383],
        [ 0.9259,  0.8722, -0.0529,  0.6273, -0.1627],
        [ 3.8030,  1.4720,  1.3928,  0.3691,  1.4324],
        [ 0.7160,  3.1162,  0.8997,  1.8662,  1.2300]], dtype=torch.float64)
