# 读写`Tensor`

我们可以直接使用`save`函数和`load`函数分别存储和读取`Tensor`。`save`使用Python的pickle实用程序将对象进行序列化，然后将序列化的对象保存到disk，使用`save`可以保存各种对象,包括模型、张量和字典等。而`laod`使用pickle unpickle工具将pickle的对象文件反序列化为内存。

In [1]:
import torch
import torch.nn as nn
x = torch.ones(10,10)
torch.save(x, 'torch_tensor.pt')

In [2]:
x2 = torch.load('torch_tensor.pt')

In [3]:
print(x2)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


## 保存多个数值

In [4]:
y = torch.randn(10,3)
print(y)

tensor([[-2.5419, -0.7828,  2.2660],
        [ 1.4686,  1.2446,  0.2236],
        [-1.9682, -0.5037,  0.7953],
        [ 1.4887, -0.9525,  1.2626],
        [ 1.3031, -0.4794, -0.8049],
        [-0.3305, -0.4776,  1.4256],
        [-0.6929, -0.5186,  0.5603],
        [-0.3428,  1.8788, -2.9109],
        [-0.9581,  0.8089, -2.0876],
        [ 1.3026,  0.3579,  0.2294]])


## 保存 tensor list

In [5]:
torch.save([x2,y], 'torch_tensor.pt')
tensor_list = torch.load('torch_tensor.pt')
print(tensor_list)

[tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]), tensor([[-2.5419, -0.7828,  2.2660],
        [ 1.4686,  1.2446,  0.2236],
        [-1.9682, -0.5037,  0.7953],
        [ 1.4887, -0.9525,  1.2626],
        [ 1.3031, -0.4794, -0.8049],
        [-0.3305, -0.4776,  1.4256],
        [-0.6929, -0.5186,  0.5603],
        [-0.3428,  1.8788, -2.9109],
        [-0.9581,  0.8089, -2.0876],
        [ 1.3026,  0.3579,  0.2294]])]


## 保存 tensor dict

In [6]:
torch.save({'x': x2, 'y': y}, 'xy_dict.pt')
xy = torch.load('xy_dict.pt')
xy

{'x': tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
 'y': tensor([[-2.5419, -0.7828,  2.2660],
         [ 1.4686,  1.2446,  0.2236],
         [-1.9682, -0.5037,  0.7953],
         [ 1.4887, -0.9525,  1.2626],
         [ 1.3031, -0.4794, -0.8049],
         [-0.3305, -0.4776,  1.4256],
         [-0.6929, -0.5186,  0.5603],
         [-0.3428,  1.8788, -2.9109],
         [-0.9581,  0.8089, -2.0876],
         [ 1.3026,  0.3579,  0.2294]])}

# 读写模型 保存读取Models 两种方式，保存参数数据，直接保存整个模型，包括结构。

## State_dict
在PyTorch中，`Module`的可学习参数(即权重和偏差)，模块模型包含在参数中(通过`model.parameters()`访问)。`state_dict`是一个从参数名称隐射到参数`Tesnor`的字典对象。

In [11]:
net = nn.Sequential(nn.Linear(16,8), nn.Linear(8,4), nn.Linear(4,1))
print(net)

Sequential(
  (0): Linear(in_features=16, out_features=8, bias=True)
  (1): Linear(in_features=8, out_features=4, bias=True)
  (2): Linear(in_features=4, out_features=1, bias=True)
)


In [13]:
print(net.state_dict())
x = torch.randn(10,16)
out = net(x)
print(out)

OrderedDict([('0.weight', tensor([[-0.1339,  0.2346,  0.0192,  0.1139,  0.0898,  0.1516,  0.0913, -0.0144,
          0.0050,  0.2099,  0.1162,  0.2429,  0.1038, -0.2080, -0.2071, -0.0356],
        [ 0.1361,  0.1636,  0.1937, -0.1632,  0.1032, -0.1234,  0.2356, -0.1315,
          0.1571,  0.2253,  0.2193,  0.0250, -0.1944, -0.2218,  0.1438,  0.0060],
        [-0.0194, -0.0117, -0.1306, -0.0590, -0.2017, -0.0871, -0.0803,  0.0759,
         -0.1303, -0.0033, -0.2128,  0.1022, -0.2262,  0.2253,  0.0854, -0.0593],
        [ 0.0277,  0.1002,  0.1903,  0.0194,  0.0548, -0.0804,  0.2014,  0.1247,
         -0.1616,  0.0190, -0.0128, -0.0827, -0.0739,  0.0033, -0.1306,  0.1938],
        [ 0.1922, -0.1214,  0.2355,  0.2170,  0.1320, -0.0643, -0.1851, -0.1908,
          0.0061,  0.0805,  0.2114, -0.0127, -0.2417, -0.0939, -0.0955,  0.1746],
        [-0.0571, -0.0597,  0.2226,  0.2278, -0.1634, -0.1866,  0.1152,  0.1031,
          0.2134, -0.1114, -0.0497, -0.1728,  0.2286,  0.1942,  0.2171,  0.002

注意，只有具有可学习参数的层(卷积层、线性层等)才有`state_dict`中的条目。优化器(`optim`)也有一个`state_dict`，其中包含关于优化器状态以及所使用的超参数的信息。

```python
optimizer = torch.optim.SGD(net.parameters(), lr=0.001, momentum=0.9)
optimizer.state_dict()
```

输出：

In [9]:
optimizer = torch.optim.SGD(net.parameters(), lr=0.001, momentum=0.9)
print(optimizer.state_dict())

{'state': {}, 'param_groups': [{'lr': 0.001, 'momentum': 0.9, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'params': [2021893735192, 2021893735264, 2021893735408, 2021893735480, 2021893735552, 2021893735624]}]}


##  保存和加载模型

PyTorch中保存和加载训练模型有两种常见的方法:

1. 仅保存和加载模型参数(`state_dict`)；
2. 保存和加载整个模型。

### 1. 保存和加载`state_dict`(推荐方式)

In [14]:
torch.save(net.state_dict(), 'linear_net_state_dict.pt')

In [15]:
net2 = nn.Sequential(nn.Linear(16,8), nn.Linear(8,4), nn.Linear(4,1))
net2.load_state_dict(torch.load('linear_net_state_dict.pt'))
print(net2(x))

tensor([[ 0.0910],
        [ 0.2001],
        [ 0.3428],
        [ 0.1315],
        [-0.1897],
        [ 0.0271],
        [ 0.1569],
        [ 0.1479],
        [ 0.1182],
        [ 0.2539]], grad_fn=<AddmmBackward>)


## 2. 保存和加载整个模型

这种方式应该是模型的结构，梯度等数据也都保存了。

In [17]:
torch.save(net2, 'linear_net_model.pt')

#载入pt文件就载入了整个网络
model = torch.load('linear_net_model.pt')
print(model(x))

tensor([[ 0.0910],
        [ 0.2001],
        [ 0.3428],
        [ 0.1315],
        [-0.1897],
        [ 0.0271],
        [ 0.1569],
        [ 0.1479],
        [ 0.1182],
        [ 0.2539]], grad_fn=<AddmmBackward>)


因为这`net`和`net2`都有同样的模型参数，那么对同一个输入`X`的计算结果将会是一样的。上面的输出也验证了这一点。

此外，还有一些其他使用场景，例如GPU与CPU之间的模型保存与读取、使用多块GPU的模型的存储等等，使用的时候可以参考[官方文档](https://pytorch.org/tutorials/beginner/saving_loading_models.html)。

## 小结

- 通过`save`函数和`load`函数可以很方便地读写`Tensor`。
- 通过`save`函数和`load_state_dict`函数可以很方便地读写模型的参数。