In [1]:
import torch

# 关于GPU 的操作

In [2]:
torch.cuda.is_available()

True

In [3]:
torch.cuda.device_count() # 输出 1

1

In [4]:
torch.cuda.current_device() # 输出 0

0

In [5]:
torch.cuda.get_device_name(0) 

'GeForce GTX 1070'

In [6]:
data = torch.randn(5,3)

In [7]:
data

tensor([[-1.4801,  1.0614,  0.8524],
        [-2.5571, -0.5740,  0.6133],
        [-0.7580, -0.3813, -0.1658],
        [ 0.2285,  2.3682,  0.6004],
        [ 0.1800,  2.1765, -0.5765]])

In [8]:
data.cuda(0)

tensor([[-1.4801,  1.0614,  0.8524],
        [-2.5571, -0.5740,  0.6133],
        [-0.7580, -0.3813, -0.1658],
        [ 0.2285,  2.3682,  0.6004],
        [ 0.1800,  2.1765, -0.5765]], device='cuda:0')

使用`.cuda()`可以将CPU上的`Tensor`转换（复制）到GPU上。如果有多块GPU，我们用`.cuda(i)`来表示第 $i$ 块GPU及相应的显存（$i$从0开始）且`cuda(0)`和`cuda()`等价。

In [10]:
data = data.cuda(0)

In [11]:
data 

tensor([[-1.4801,  1.0614,  0.8524],
        [-2.5571, -0.5740,  0.6133],
        [-0.7580, -0.3813, -0.1658],
        [ 0.2285,  2.3682,  0.6004],
        [ 0.1800,  2.1765, -0.5765]], device='cuda:0')

In [12]:
data.device

device(type='cuda', index=0)

需要注意的是，存储在不同位置中的数据是不可以直接进行计算的。即存放在CPU上的数据不可以直接与存放在GPU上的数据进行运算，位于不同GPU上的数据也是不能直接进行计算的。

In [14]:
data2 = torch.randn(1,3)
print(data+data2)
    


RuntimeError: expected backend CUDA and dtype Float but got backend CPU and dtype Float

In [15]:
print(data.cpu()+data2)

tensor([[-2.3710e+00,  3.2192e-01,  1.4285e+00],
        [-3.4480e+00, -1.3135e+00,  1.1895e+00],
        [-1.6488e+00, -1.1207e+00,  4.1037e-01],
        [-6.6238e-01,  1.6288e+00,  1.1765e+00],
        [-7.1088e-01,  1.4370e+00, -3.1453e-04]])


## 模型的GPU计算

同`Tensor`类似，PyTorch模型也可以通过`.cuda`转换到GPU上。我们可以通过检查模型的参数的`device`属性来查看存放模型的设备。

In [19]:

net = torch.nn.Sequential(torch.nn.Linear(3,5), torch.nn.Linear(5,1))
net.to('cuda')

Sequential(
  (0): Linear(in_features=3, out_features=5, bias=True)
  (1): Linear(in_features=5, out_features=1, bias=True)
)

同`Tensor`类似，PyTorch模型也可以通过`.cuda`转换到GPU上。我们可以通过检查模型的参数的`device`属性来查看存放模型的设备。

In [20]:
net(data)

tensor([[ 0.2074],
        [-0.2366],
        [-0.0859],
        [ 0.6179],
        [ 0.7629]], device='cuda:0', grad_fn=<AddmmBackward>)

In [22]:
list(net[0].parameters())[0].device

device(type='cuda', index=0)